### PR TITLE
Updating EquipmentController to autobind

### PR DESCRIPTION
**Pull request by glauco**
Given we are require to bind class methods to have `this`, we moved that
logic to happen on the class constructor.
This removes the burden from the caller, making classes easier to consume.

### CODE REVIEW

**Comment by bltavares** [comment]
:-1: 
We don't need to use bind if the idea is to move it into another scenario. Binding the functions on itself could be misleading as we cannot redefine the this on that case anymore.

We could simply wrap the handler with an anonymous function so we don't remove the binding of this when calling the function on the object:

```javascript
handler: (request, response) => equipmentController.findAll(request, response),
```

**Comment by glauco** [comment]
On the case, specifically, creating a wrapper only includes noise.

I don't see any harm in implementing this kind of autobinding.

What would be other scenarios where we would need to bind a class instance to another instance?

**Comment by ramalho** [comment]
I support @glauco 's solution. I believe simplifying the common use cases is more important than maximizing flexibility in this context, We are working on a user-friendly API, after all.

**Comment by bltavares** [comment]
The expected behavior on functions of JavaScript objects is to be unbound when extracted from the object. This happens on all scenarios, including the standard objects methods.

```javascript
var list = [1, 2, 3];
list.sort // unbound method
```

I would be very surprised on that case if I try to crate a new object and not being able to bind it to another thing I want:

```javascript
var obj = new MyObjc();
obj.doSomething.call(anotherObj);
```

This would break some of the functionalities with other functions, for example on `forEach`, which could take a function and a this to handle things.

```javascript
var sorter = myList.sort;
thisIsNotARealList.forEach(sorter, anotherList) // this of sorter bound to another list on the forEach context
```

If bind is not a desired idiom, I would rather not have it at all, instead of surprising behaviors.

**Comment by glauco** [comment]
While I agree with you, that this is the standard JavaScript behavior, I would be surprised if someone extracted a method out of a class. That is certainly not the behavior I would expect while consuming real classes.

**Comment by ramalho** [comment]
The problem @glauco is that there are no real classes in JavaScript, and there are many ways of "faking" classes. I have not grasped yet how the "official" classes are supposed to work in ES2015. We should adhere to that if we want to have class-like behavior.

**Comment by ramalho** [comment]
using a method as an unbound function is very useful when programming in a functional style. @bruno's example of forEach is an instance of that. in Python, that is the may reason for the explicit self argument in function signatures: it makes it explicit that you must pass the receiver object as the first arg when using a method as an unbound function

**Comment by bltavares** [comment]
`bind` is a common idiom on JavaScript-land, and it is something I expect on more `functional OO` style code.

If we would rather not use a common idiom, I don't think we should bring behaviors from other languages. It is a bit unfair to bring expectations from other languages to JavaScript.

**Comment by jeffhsta** [comment]
I agree with all arguments, as @bltavares said this is the way that javascript do this, but I would like to accept the @glauco 's solution, it make sense if what is going to consume this class keep the class scope. I don't see any other reason to change the scope of the functions of this class.

I prefer have an easier way to call those function without have to bind every time those will be called

**Comment by glauco** [comment]
I would only support the usage of classes, if they behave in a similar way as the rest of the world.

If we don't want to bring this behavior, I think we should reconsider the usage of classes at all.

**Comment by bltavares** [comment]
There is a solution that does not require the use of `bind`, nor break the expected behavior of methods on objects in JavaScript.

The noise added is actually making the arguments explicit.
This leads me to see that the handler takes a request and a response. We could probably refactor the `findAll` to be decouple from the `request` structure, taking only the needed information, as it could be used from other places on the code base as well.

Another solution could be to create a handler function on the scope, that will decouple the findAll from the request:

```javascript
const handler = (request, response) {
  let id = request.id;
  let bearer = request.header.Bearer;
  controller.findAll(id, bearer).then(response)
}
```

**Comment by glauco** [comment]
All these solutions require the called to know the implementation details of the function/method. That is exactly the problem you don't want to tackle when using classes, because after all, you just want methods that encapsulate the complexity for you.

Adding boilerplate code just to fit with the regular JavaScript style, in my perspective, only seem to be including unnecessary complexity.

**Comment by glauco** [comment]
Also, if we don't want to go that way, we could just get rid of `this` pointers and be more explicit. :)

**Comment by andressa** [comment]
I also agree with Glaucos proposed solution.

**Comment by waldemarnt** [comment]
I agree with @bltavares this is a common behaviour in javascript. But in my point of view we are discussing about the Class syntax responsibility and not only about of the bind itself.

Classes should have the responsibility of your own scope like the common languages such as C#, Ruby, Java. In javascript classes are only a prototype encapsulation, sure does make sense thinking about composition but the real "Class"responsibility is overriden in my point of view. The solution that @glauco did, in other hand make sense when we think about of class responsibility.

We don't know about the future of javascript, but make sense this classes manage your own scope also inside functions that are declared inside them, we already had changes to make JS more flexible like arrow functions that use the same scope of the context that they was been declared. I think in the future we will have a way to do the same think as glauco did in a automatic way.

My answer is: I agree with @glauco in this class that is a controller and wants to be used with Hapi that this bind will be mandatory, but we shouldn't do this auto bind for all Classes.

**Comment by bltavares** [comment]
Given we are going with this, I have a few questions:

1. Which scenarios would we use this pattern?
2. How to tell if a method is already bound or not?
3. If we introduce another method on the controller, that will not be used by Hapi, should we follow this pattern?
4. Should all our objects follow this convention?
5. What to do with 3rd party objects that don't follow our convention?

**Comment by glauco** [comment]
1. I would use this wherever I need more than one property that the instance already have. If I don't need an instance value, I would not use it.
2. As a consumer, I would assume all methods from a class are bounded and not safe to be used outside context (unless they are 'static').
3. As explained in 1, it will depend.
4. As explained in 3, it will depend.
5. What do you mean by 3rd party objects?

**Comment by bltavares** [comment]
5. Classes from other packages, eg: Hapi

**Comment by bltavares** [comment]
One interesting information, bound functions cannot be rebound. Not sure if that would make any difference on the arguments

```
> a = function () { return this }
[Function]
> b = function.bind({})
... ;
...
> b = a.bind({})
[Function: bound ]
> c = b.bind(1)
[Function: bound bound ]
> c()
{}
```

**Comment by glauco** [comment]
As far as I know, Hapi do not use classes, but constructor functions and prototypes.

**Comment by glauco** [comment]
This seem to be only a bias from my side toward JavaScript.

After Bruno's explanation, I feel more informed and believe that including this sort of magic "breaks the language".

**Pull request closed without merging**
