### PR TITLE
Changes logging logic

### PR DESCRIPTION
**Pull request by carolinaborim**
Based on discussions that we had today about the logging responsability, we changed the way that we are writing logs to be more generic.
The responsability to define in which index and type the data will be saved
was moved to logstash.
co-author: @waldemarnt

### CODE REVIEW

**Comment by glauco** [comment]
LGTM!

**Comment by andressa** [comment]
👍

**Comment by lucaslago** [comment]
👍

**Comment by andressa** [comment]
Why do we have an empty file in log/?

**Pull request merged**
