### PR TITLE
Update Codeclimate definitions

### PR DESCRIPTION
**Pull request by glauco**
Codeclimate does not support our eslint configuration. Given that
we decided to give up using Codeclimate's eslint.

### CODE REVIEW

**Comment by bltavares** [comment]
Are we still going to be verifying the code using our linting configuration?

**Comment by bltavares** [comment]
For reference, this is the issue discussing CodeClimate's support to third-party configuration
https://github.com/codeclimate/codeclimate-eslint/issues/4

**Comment by glauco** [comment]
@bltavares Wes! We will keep running `eslint` as part of `npm test`.

**Comment by bltavares** [comment]
LGTM then

**Comment by waldemarnt** [comment]
As I understood the eslint.rc has been used by code climate, there's no impact removing that.
:+1:

**Pull request merged**
