### PR TITLE
Moves business logic to source dir

### PR DESCRIPTION
**Pull request by waldemarnt**
@lucaslago and I are working to separate our source from the rest of the build logics.
We moved contract tests to a separate test folder inside test directory.
We separated application source code to a specific src folder to improve readability.

### CODE REVIEW

**Comment by andressa** [comment]
What is the motivation of doing it?

**Comment by waldemarnt** [comment]
@andressa we are going to have more directories in our root dir. Like "elk" to metrics, and things like that. If you check the previews version we are mixing source folders like controllers, helpers with elk and another build tools.
A directory to source code is a common pattern in node.js ecosystem. Here we have a pretty explanation of what i'm saying http://stackoverflow.com/a/5193206/4043593

**Comment by andressa** [comment]
👍

**Comment by glauco** [comment]
🐑 🇮🇹

**Pull request merged**
